### ISSUE TITLE
Graphviz syntax error in nodes with reserved words

### ISSUE THREAD

**Issue by mrichardson3** [felix-hilden/pyfactor#9]
I was experimenting with pyfactor to see how it operates and if it might help me decipher large codebases.  I decided to test it out on the googler.py codebase as my guinea pig.  Googler.py runs without a problem on my machine.  However, when I run pyfactor against this source file, this is what my terminal looks like.

(py37) mark@mark-XPS-8910:/mnt/Data/CMR/PythonPrograms$ pyfactor googler.py 
Error: <stdin>: syntax error in line 118 near '->'

I suspect this error may be a red herring, but I don't have a clue where to begin debugging the problem because there doesn't
appear to be a syntax problem around that line in the source file.  I also tried skipping imports and all it did was change the
line number of the syntax error as shown below:

(py37) mark@mark-XPS-8910:/mnt/Data/CMR/PythonPrograms$ pyfactor -si googler.py
Error: <stdin>: syntax error in line 65 near '->'

Finally, I ran the googler code through black to reformat it - figuring it would change the line numbers and I might be able to deduce a pattern.  Black increased the line count of googler.py from 3,659 to 4,100 lines.  When I ran pyfactor against the blacked code it still showed the syntax error as being on line 118.

I thought you might be interested in seeing this edge case. If not, please just close this issue as I was just exploring.

I am using version 4.3.2 of googler.py in case that would be necessary to reproduce the error.

Good Luck with the project,
over and out,
Mark R.

**Comment by felix-hilden** [comment]
Oh, thanks for the report! I assume the error is from Graphviz, referencing its graph source definition file. Would you mind doing some debugging for me? Firstly, what is your Graphviz version number? You can find out by running `dot -v`.

We'll leave the `.gv` file uncleaned with the following command: `pyfactor -si googler.py::` (note the colons). Please look at the file and paste the graph source around the correct line number here. What I'm suspecting is a [similar error](https://unix.stackexchange.com/q/630422/335240) that I already encountered with Pydot, where the graph contains nodes whose names are reserved words.

**Comment by mrichardson3** [comment]
Thanks for the extraordinarily quick response.  Hopefully, I can give you
the information you are seeking.

Here is the output from dot -v

mark@mark-XPS-8910:/mnt/Data/CMR/PythonPrograms$ dot -v
dot - graphviz version 2.40.1 (20161225.0304)
libdir = "/usr/lib/x86_64-linux-gnu/graphviz"
Activated plugin library: libgvplugin_dot_layout.so.6
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.so.6
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
/usr/lib/x86_64-linux-gnu/graphviz/config6a
was successfully loaded.
    render :  cairo dot dot_json fig gd json json0 map mp pic pov ps svg tk
vml vrml xdot xdot_json
    layout :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout :  textlayout
    device :  canon cmap cmapx cmapx_np dot dot_json eps fig gd gd2 gif gv
imap imap_np ismap jpe jpeg jpg json json0 mp pdf pic plain plain-ext png
pov ps ps2 svg svgz tk vml vmlz vrml wbmp x11 xdot xdot1.2 xdot1.4
xdot_json xlib
    loadimage :  (lib) eps gd gd2 gif jpe jpeg jpg png ps svg xbm




Because the googler.gv file is only 155 lines long, I just went on and cut
and pasted the whole thing. Yikes it looks ugly because of the font. My
apologies. If you are using your editor, line 65 is where this version of
the program blows up.
Line 65 looks like this so you can search for it directly.
Node -> Selector;

digraph  {
logger [fillcolor="#FFE0E0", label="   logger   \nV:76", shape=box,
style=filled];
sigint_handler [fillcolor="#E5E5E5", label="sigint_handler\nF:79",
shape=ellipse, style=filled];
_VERSION_ [fillcolor="#FFE0E0", label=" _VERSION_  \nV:92", shape=box,
style=filled];
_EPOCH_ [fillcolor="#E4FFE4", label="  _EPOCH_   \nV:93", shape=box,
style=filled];
COLORMAP [fillcolor="#E4FFE4", label="  COLORMAP  \nV:95", shape=box,
style=filled];
USER_AGENT [fillcolor="#E4FFE4", label=" USER_AGENT \nV:107", shape=box,
style=filled];
text_browsers [fillcolor="#E4FFE4", label="text_browsers\nV:109",
shape=box, style=filled];
ENABLE_SELF_UPGRADE_MECHANISM [fillcolor="#E4FFE4",
label="ENABLE_SELF_UPGRADE_MECHANISM\nV:120", shape=box, style=filled];
API_REPO_BASE [fillcolor="#E4FFE4", label="API_REPO_BASE\nV:121",
shape=box, style=filled];
RAW_DOWNLOAD_REPO_BASE [fillcolor="#E4FFE4",
label="RAW_DOWNLOAD_REPO_BASE\nV:122", shape=box, style=filled];
debugger [fillcolor="#E4FFE4", label="  debugger  \nV:124", shape=box,
style=filled];
monkeypatch_textwrap_for_cjk [fillcolor="#E5E5E5",
label="monkeypatch_textwrap_for_cjk\nF:129", shape=ellipse, style=filled];
CoordinateType [fillcolor="#E4FFE4", label="CoordinateType\nV:171",
shape=box, style=filled];
TrackedTextwrap [fillcolor="#FFFFFF", label="TrackedTextwrap\nC:174",
shape=parallelogram, style=filled];
SelectorGroupLike [fillcolor="#E4FFE4", label="SelectorGroupLike\nV:272",
shape=box, style=filled];
Node [fillcolor="#FFE0E0", label="    Node    \nC:275",
shape=parallelogram, style=filled];
Selector [fillcolor="#FFE0E0", label="  Selector  \nC:851",
shape=parallelogram, style=filled];
ElementNode [fillcolor="#FFE0E0", label="ElementNode \nC:502",
shape=parallelogram, style=filled];
SelectorGroup [fillcolor="#FFFFFF", label="SelectorGroup\nC:790",
shape=parallelogram, style=filled];
TextNode [fillcolor="#FFE0E0", label="  TextNode  \nC:578",
shape=parallelogram, style=filled];
_tag_is_void [fillcolor="#E4FFE4", label="_tag_is_void\nF:1340",
shape=ellipse, style=filled];
DOMBuilderException [fillcolor="#E4FFE4",
label="DOMBuilderException\nC:619", shape=parallelogram, style=filled];
DOMBuilder [fillcolor="#FFE0E0", label=" DOMBuilder \nC:637",
shape=parallelogram, style=filled];
_tag_encloses_foreign_namespace [fillcolor="#E4FFE4",
label="_tag_encloses_foreign_namespace\nF:1364", shape=ellipse,
style=filled];
parse_html [fillcolor="#FFFFFF", label=" parse_html \nF:747",
shape=ellipse, style=filled];
SelectorParserException [fillcolor="#E4FFE4",
label="SelectorParserException\nC:765", shape=parallelogram, style=filled];
AttributeSelector [fillcolor="#FFFFFF", label="AttributeSelector\nC:1232",
shape=parallelogram, style=filled];
AttributeSelectorType [fillcolor="#E4FFE4",
label="AttributeSelectorType\nC:1291", shape=parallelogram, style=filled];
Combinator [fillcolor="#E4FFE4", label=" Combinator \nC:1320",
shape=parallelogram, style=filled];
open_url [fillcolor="#FFE0E0", label="  open_url  \nF:1377", shape=ellipse,
style=filled];
printerr [fillcolor="#FFE0E0", label="  printerr  \nF:1434", shape=ellipse,
style=filled];
unwrap [fillcolor="#E4FFE4", label="   unwrap   \nF:1441", shape=ellipse,
style=filled];
check_stdout_encoding [fillcolor="#FFFFFF",
label="check_stdout_encoding\nF:1458", shape=ellipse, style=filled];
time_it [fillcolor="#FFFFFF", label="  time_it   \nF:1494", shape=ellipse,
style=filled];
HardenedHTTPSConnection [fillcolor="#FFFFFF",
label="HardenedHTTPSConnection\nC:1516", shape=parallelogram, style=filled];
GoogleUrl [fillcolor="#E4FFE4", label=" GoogleUrl  \nC:1602",
shape=parallelogram, style=filled];
GoogleConnectionError [fillcolor="#E4FFE4",
label="GoogleConnectionError\nC:1968", shape=parallelogram, style=filled];
GoogleConnection [fillcolor="#FFE0E0", label="GoogleConnection\nC:1972",
shape=parallelogram, style=filled];
parse_proxy_spec [fillcolor="#E4FFE4", label="parse_proxy_spec\nF:3359",
shape=ellipse, style=filled];
GoogleParser [fillcolor="#FFE0E0", label="GoogleParser\nC:2202",
shape=parallelogram, style=filled];
Result [fillcolor="#FFFFFF", label="   Result   \nC:2418",
shape=parallelogram, style=filled];
Sitelink [fillcolor="#E4FFE4", label="  Sitelink  \nC:2395",
shape=parallelogram, style=filled];
Colors [fillcolor="#E4FFE4", label="   Colors   \nV:2415", shape=box,
style=filled];
GooglerCmdException [fillcolor="#E4FFE4",
label="GooglerCmdException\nC:2584", shape=parallelogram, style=filled];
NoKeywordsException [fillcolor="#FFFFFF",
label="NoKeywordsException\nC:2588", shape=parallelogram, style=filled];
require_keywords [fillcolor="#FFFFFF", label="require_keywords\nF:2592",
shape=ellipse, style=filled];
no_argument [fillcolor="#FFFFFF", label="no_argument \nF:2604",
shape=ellipse, style=filled];
GooglerCmd [fillcolor="#FFA0A0", label=" GooglerCmd \nC:2619",
shape=parallelogram, style=filled];
GooglerArgumentParser [fillcolor="#FFE0E0",
label="GooglerArgumentParser\nC:3076", shape=parallelogram, style=filled];
system_is_windows [fillcolor="#E4FFE4", label="system_is_windows\nF:3184",
shape=ellipse, style=filled];
get_latest_ref [fillcolor="#FFFFFF", label="get_latest_ref\nF:3189",
shape=ellipse, style=filled];
download_latest_googler [fillcolor="#FFE0E0",
label="download_latest_googler\nF:3212", shape=ellipse, style=filled];
self_replace [fillcolor="#FFFFFF", label="self_replace\nF:3250",
shape=ellipse, style=filled];
self_upgrade [fillcolor="#FFE0E0", label="self_upgrade\nF:3288",
shape=ellipse, style=filled];
check_new_version [fillcolor="#FFFFFF", label="check_new_version\nF:3302",
shape=ellipse, style=filled];
python_version [fillcolor="#E4FFE4", label="python_version\nF:3351",
shape=ellipse, style=filled];
https_proxy_from_environment [fillcolor="#E4FFE4",
label="https_proxy_from_environment\nF:3355", shape=ellipse, style=filled];
set_win_console_mode [fillcolor="#E4FFE4",
label="set_win_console_mode\nF:3388", shape=ellipse, style=filled];
completer_fetch_completions [fillcolor="#FFFFFF",
label="completer_fetch_completions\nF:3421", shape=ellipse, style=filled];
completer_run [fillcolor="#FFFFFF", label="completer_run\nF:3452",
shape=ellipse, style=filled];
parse_args [fillcolor="#FFE0E0", label=" parse_args \nF:3460",
shape=ellipse, style=filled];
main [fillcolor="#FFA0A0", label="    main    \nF:3563", shape=ellipse,
style=filled];
TrackedTextwrap -> CoordinateType;
Node -> Selector;
Node -> ElementNode;
Node -> SelectorGroupLike;
Node -> SelectorGroup;
Selector -> AttributeSelector;
Selector -> AttributeSelectorType;
Selector -> Combinator;
Selector -> ElementNode;
Selector -> SelectorParserException;
ElementNode -> TextNode;
ElementNode -> Node;
ElementNode -> _tag_is_void;
SelectorGroup -> Selector;
SelectorGroup -> SelectorParserException;
TextNode -> Node;
DOMBuilder -> _tag_encloses_foreign_namespace;
DOMBuilder -> TextNode;
DOMBuilder -> ElementNode;
DOMBuilder -> DOMBuilderException;
DOMBuilder -> _tag_is_void;
parse_html -> DOMBuilder;
AttributeSelector -> AttributeSelectorType;
open_url -> logger;
open_url -> open_url;
open_url -> text_browsers;
check_stdout_encoding -> unwrap;
time_it -> logger;
HardenedHTTPSConnection -> logger;
GoogleConnection -> GoogleConnectionError;
GoogleConnection -> parse_proxy_spec;
GoogleConnection -> logger;
GoogleConnection -> HardenedHTTPSConnection;
GoogleConnection -> USER_AGENT;
GoogleConnection -> time_it;
GoogleParser -> printerr;
GoogleParser -> Result;
GoogleParser -> logger;
GoogleParser -> TextNode;
GoogleParser -> Sitelink;
GoogleParser -> time_it;
GoogleParser -> parse_html;
GoogleParser -> debugger;
Result -> TrackedTextwrap;
NoKeywordsException -> GooglerCmdException;
require_keywords -> NoKeywordsException;
no_argument -> logger;
GooglerCmd -> NoKeywordsException;
GooglerCmd -> GooglerArgumentParser;
GooglerCmd -> no_argument;
GooglerCmd -> GoogleUrl;
GooglerCmd -> printerr;
GooglerCmd -> GoogleConnection;
GooglerCmd -> logger;
GooglerCmd -> RAW_DOWNLOAD_REPO_BASE;
GooglerCmd -> open_url;
GooglerCmd -> _EPOCH_;
GooglerCmd -> require_keywords;
GooglerCmd -> GoogleParser;
GooglerArgumentParser -> _VERSION_;
GooglerArgumentParser -> COLORMAP;
get_latest_ref -> API_REPO_BASE;
download_latest_googler -> get_latest_ref;
download_latest_googler -> printerr;
download_latest_googler -> RAW_DOWNLOAD_REPO_BASE;
self_replace -> system_is_windows;
self_upgrade -> self_replace;
self_upgrade -> download_latest_googler;
self_upgrade -> printerr;
check_new_version -> _VERSION_;
check_new_version -> get_latest_ref;
completer_fetch_completions -> logger;
completer_run -> completer_fetch_completions;
parse_args -> GooglerArgumentParser;
parse_args -> system_is_windows;
parse_args -> _VERSION_;
parse_args -> https_proxy_from_environment;
parse_args -> ENABLE_SELF_UPGRADE_MECHANISM;
main -> check_new_version;
main -> check_stdout_encoding;
main -> set_win_console_mode;
main -> logger;
main -> _VERSION_;
main -> python_version;
main -> text_browsers;
main -> completer_run;
main -> self_upgrade;
main -> COLORMAP;
main -> Colors;
main -> parse_args;
main -> debugger;
}

**Comment by felix-hilden** [comment]
Yeah, so most likely the "node" is a reserved word. I think the fix would be to introduce some prefix to each node, leaving the labels intact so that these kinds of issues wouldn't bother users anymore. It's quite unintuitive, and it *has* been fixed in later versions. But seeing that you are on some brand of Linux, I'm guessing a Debian variant of some kind, the repositories haven't updated yet, and they won't for a long time 😅

Much appreciated! I'll edit the issue a bit for housekeeping.

**Comment by felix-hilden** [comment]
This should be fixed now, though not released yet, as you can see from similar output in our Gallery [here](https://pyfactor.readthedocs.io/en/latest/gallery/pydot.html). Thanks a bunch again for reporting it @mrichardson3
